production:
  solr:
    hostname: staging.justbooksclc.com
    port: 8983
    user: ENV['SOLR'],
    password: ENV['SOLR_PASSWORD'],
    log_level: WARNING
  auto_commit_after_request: false


development:
  solr:
    hostname: localhost
    port: 8983

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
