x = []
x << {:cust_iti_name => 'Ghanshyam-Pondicherry', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '15 May, 2011', :trip_end_date => '18 May, 2011', :seasons => 'Summer', :duration => 3, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Dhiwakar-Wayanad', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '22 April, 2011', :trip_end_date => '25 May, 2011', :seasons => 'Summer', :duration => 3, :no_of_adults => 6, :no_of_children => 0 }
x << {:cust_iti_name => 'Sundar Rajan', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '18 July, 2011', :trip_end_date => '31 July, 2011', :seasons => 'Monsoon', :duration => 13, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Kannan P', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '4 July, 2011', :trip_end_date => '8 July, 2011', :seasons => 'Monsoon', :duration => 4, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Vinod Shankar', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '30 June, 2011', :trip_end_date => '03 July, 2011', :seasons => 'Monsoon', :duration => 3, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Subhash Bhushan', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '8 October, 2011', :trip_end_date => '14 October, 2011', :seasons => 'Winter', :duration => 6, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Dilshad Billimoria', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '12 August, 2011', :trip_end_date => '15 August, 2011', :seasons => 'Monsoon', :duration => 3, :no_of_adults => 2, :no_of_children => 2 }
x << {:cust_iti_name => 'Fred ', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '15 August, 2011', :trip_end_date => '18 August, 2011', :seasons => 'Monsoon', :duration => 3, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Puja Sharma', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '28 September, 2011', :trip_end_date => '30 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 3, :no_of_children => 0 }
x << {:cust_iti_name => 'Ram J', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '31 August, 2011', :trip_end_date => '2 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Hena James', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '1 September, 2011', :trip_end_date => '3 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 3, :no_of_children => 0 }
x << {:cust_iti_name => 'Kalaiselvi', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '2 September, 2011', :trip_end_date => '5 September, 2011', :seasons => 'Monsoon', :duration => 3, :no_of_adults => 2, :no_of_children => 1 }
x << {:cust_iti_name => 'Swathi', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '2 September, 2011', :trip_end_date => '4 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 4, :no_of_children => 0 }
x << {:cust_iti_name => 'Nirmala', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '2 September, 2011', :trip_end_date => '5 September, 2011', :seasons => 'Monsoon', :duration => 3, :no_of_adults => 2, :no_of_children => 1 }
x << {:cust_iti_name => 'Ashwin Ramachandran', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '1 September, 2011', :trip_end_date => '3 September, 2011', :seasons => 'Monsoon', :duration => 1, :no_of_adults => 4, :no_of_children => 1 }
x << {:cust_iti_name => 'Partha', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '9 September, 2011', :trip_end_date => '11 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Lohit', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '9 September, 2011', :trip_end_date => '12 September, 2011', :seasons => 'Monsoon', :duration => 3, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Rakesh Babu', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '20 September, 2011', :trip_end_date => '22 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 4, :no_of_children => 0 }
x << {:cust_iti_name => 'Lokesh Ramachandran', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '9 September, 2011', :trip_end_date => '11 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Nikhil S', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '4 September, 2011', :trip_end_date => '6 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Suresh S', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '14 September, 2011', :trip_end_date => '16 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 3, :no_of_children => 0 }
x << {:cust_iti_name => 'Varna Kumari', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '10 September, 2011', :trip_end_date => '12 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Daphne Jennifer', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '16 September, 2011', :trip_end_date => '19 September, 2011', :seasons => 'Monsoon', :duration => 3, :no_of_adults => 2, :no_of_children => 2 }
x << {:cust_iti_name => 'Naveen', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '10 September, 2011', :trip_end_date => '12 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Supreet', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '15 September, 2011', :trip_end_date => '17 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 4, :no_of_children => 0 }
x << {:cust_iti_name => 'Vikas', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '17 September, 2011', :trip_end_date => '19 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 1, :no_of_children => 0 }
x << {:cust_iti_name => 'Pawan Kumar', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '23 September, 2011', :trip_end_date => '26 September, 2011', :seasons => 'Monsoon', :duration => 3, :no_of_adults => 6, :no_of_children => 0 }
x << {:cust_iti_name => 'Kavya Hegde', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '11 September, 2011', :trip_end_date => '12 September, 2011', :seasons => 'Monsoon', :duration => 1, :no_of_adults => 4, :no_of_children => 0 }
x << {:cust_iti_name => 'Manjula P', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '22 September, 2011', :trip_end_date => '24 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Raghavendra', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '21 September, 2011', :trip_end_date => '23 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 3, :no_of_children => 0 }
x << {:cust_iti_name => 'Satish Krishnamurthy', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '17 September, 2011', :trip_end_date => '19 September, 2011', :seasons => 'Monsoon', :duration => 2, :no_of_adults => 2, :no_of_children => 1 }
x << {:cust_iti_name => 'Kamala Sheshadiri', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '25 September, 2011', :trip_end_date => '27 September, 2011', :seasons => 'Monsoon', :duration => 3, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Padmini Mazumder', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '23 September, 2011', :trip_end_date => '24 September, 2011', :seasons => 'Monsoon', :duration => 1, :no_of_adults => 3, :no_of_children => 0 }
x << {:cust_iti_name => 'Atul & Abhishek', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '24 December, 2011', :trip_end_date => '26 December, 2011', :seasons => 'Post monsoon', :duration => 2, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Sujit Williams', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '30 October, 2011', :trip_end_date => '1 November, 2011', :seasons => 'Post monsoon', :duration => 2, :no_of_adults => 4, :no_of_children => 2 }
x << {:cust_iti_name => 'Ravikumar', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '7 October, 2011', :trip_end_date => '10 October, 2011', :seasons => 'Post monsoon', :duration => 3, :no_of_adults => 3, :no_of_children => 2 }
x << {:cust_iti_name => 'Shanthakumari', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '15 Dec, 2012', :trip_end_date => '17 Dec, 2012', :seasons => 'Post monsoon', :duration => 2, :no_of_adults => 2, :no_of_children => 1 }
x << {:cust_iti_name => 'Sapna Rawat', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '19 May, 2012', :trip_end_date => '21 May, 2012', :seasons => 'Summer', :duration => 2, :no_of_adults => 2, :no_of_children => 2 }
x << {:cust_iti_name => 'Mahesh Menon', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '10 Feb, 2012', :trip_end_date => '13 Feb, 2012', :seasons => 'Winter', :duration => 3, :no_of_adults => 2, :no_of_children => 2 }
x << {:cust_iti_name => 'Mamatha Kamath', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '09 Feb, 2012', :trip_end_date => '12 Feb, 2012', :seasons => 'Winter', :duration => 3, :no_of_adults => 2, :no_of_children => 2 }
x << {:cust_iti_name => 'Sonal Rao', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '16 Feb, 2012', :trip_end_date => '20 Feb, 2012', :seasons => 'Winter', :duration => 4, :no_of_adults => 2, :no_of_children => 1 }
x << {:cust_iti_name => 'Krishnaraja  Reddy ', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '11 May, 2012', :trip_end_date => '18 May, 2011', :seasons => 'Summer', :duration => 7, :no_of_adults => 3, :no_of_children => 0 }
x << {:cust_iti_name => 'Ulka kelkar', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '16 Jan, 2012', :trip_end_date => '18 Jan, 2012', :seasons => 'Winter', :duration => 2, :no_of_adults => 2, :no_of_children => 1 }
x << {:cust_iti_name => 'Sonde A S', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '26 Feb, 2012', :trip_end_date => '01 March, 2012', :seasons => 'Summer', :duration => 3, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Shubha Ragavendra', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '26 Jan, 2012', :trip_end_date => '29 Jan, 2012', :seasons => 'Winter', :duration => 3, :no_of_adults => 2, :no_of_children => 2 }
x << {:cust_iti_name => 'Dr. Archana Shetty', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '5 Feb, 2012', :trip_end_date => '7 Feb, 2012', :seasons => 'Winter', :duration => 2, :no_of_adults => 2, :no_of_children => 1 }
x << {:cust_iti_name => 'Poornima Subraminian', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '14 Feb, 2012', :trip_end_date => '18 Feb, 2012', :seasons => 'Winter', :duration => 4, :no_of_adults => 2, :no_of_children => 1 }
x << {:cust_iti_name => 'Radhika Nagaraja', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '26 Jan, 2012', :trip_end_date => '29 Jan, 2012', :seasons => 'Winter', :duration => 3, :no_of_adults => 2, :no_of_children => 1 }
x << {:cust_iti_name => 'Archana Saraf', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '18 Feb, 2012', :trip_end_date => '21 Feb, 2012', :seasons => 'Winter', :duration => 3, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'P. Jyothirmayee', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '10 Feb, 2012', :trip_end_date => '13 Feb, 2012', :seasons => 'Winter', :duration => 3, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Karthik Chintapatla', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '11 Jan, 2012', :trip_end_date => '14 Jan, 2012', :seasons => 'Winter', :duration => 3, :no_of_adults => 2, :no_of_children => 1 }
x << {:cust_iti_name => 'Priti Mehta', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '20 Jan, 2012', :trip_end_date => '22 Jan, 2012', :seasons => 'Winter', :duration => 2, :no_of_adults => 2, :no_of_children => 1 }
x << {:cust_iti_name => 'Bindu pal', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '29 March, 2012', :trip_end_date => '01 June, 2012', :seasons => 'Summer', :duration => 3, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Srivatsav', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '03 November, 2012', :trip_end_date => '07 November, 2012', :seasons => 'Post monsoon', :duration => 4, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Tejas Dinkar', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '24 July, 2012', :trip_end_date => '28 July, 2012', :seasons => 'Monsoon', :duration => 4, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Seema Menon', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '18 September, 2012', :trip_end_date => '23 September, 2012', :seasons => 'Monsoon', :duration => 5, :no_of_adults => 4, :no_of_children => 2 }
x << {:cust_iti_name => 'Chethan R', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '16 April, 2013', :trip_end_date => '21 April, 2013', :seasons => 'Summer', :duration => 5, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Shajin S', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '24 Jan, 2013', :trip_end_date => '27 Jan, 2013', :seasons => 'Winter', :duration => 3, :no_of_adults => 4, :no_of_children => 0 }
x << {:cust_iti_name => 'Sheela/Deepti', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '6 April, 2013', :trip_end_date => '12 April, 2013', :seasons => 'Summer', :duration => 6, :no_of_adults => 4, :no_of_children => 3 }
x << {:cust_iti_name => 'Sivaramakrishnan', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '27 Dec, 2012', :trip_end_date => '29 Dec, 2012', :seasons => 'Post monsoon', :duration => 2, :no_of_adults => 4, :no_of_children => 3 }
x << {:cust_iti_name => 'Chaitra Balakrishnan', :iti_type => 'Single', :vacation_type_id => 2, :trip_start_date => '20 July, 2013', :trip_end_date => '25 July, 2013', :seasons => 'Monsoon', :duration => 5, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Mamtha', :iti_type => 'Multiple', :vacation_type_id => 2, :trip_start_date => '4 October, 2013', :trip_end_date => '6 October, 2013', :seasons => 'Post monsoon', :duration => 2, :no_of_adults => 2, :no_of_children => 2 }
x << {:cust_iti_name => 'Sunil Kumar', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '14 Jan, 2013', :trip_end_date => '17 Jan, 2013', :seasons => 'Winter', :duration => 4, :no_of_adults => 2, :no_of_children => 0 }
x << {:cust_iti_name => 'Padmini Mazumder', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '14 April, 2012', :trip_end_date => '16 April, 2012', :seasons => 'Summer', :duration => 2, :no_of_adults => 3, :no_of_children => 0 }
x << {:cust_iti_name => 'Nikhil Sivakumar', :iti_type => 'Single', :vacation_type_id => 1, :trip_start_date => '25 October, 2012', :trip_end_date => '28 October, 2012', :seasons => 'Post monsoon', :duration => 3, :no_of_adults => 2, :no_of_children => 0 }

x.each do |arg|
  cust = CustItiHeader.new(arg)
  p cust.save
end