require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustItiHeadersController do

  # This should return the minimal set of attributes required to create a valid
  # CustItiHeader. As you add validations to CustItiHeader, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.build(:cust_iti_header).attributes }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustItiHeadersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cust_iti_headers as @cust_iti_headers" do
      cust_iti_header = CustItiHeader.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cust_iti_headers).should eq([cust_iti_header])
    end
  end

  describe "GET show" do
    it "assigns the requested cust_iti_header as @cust_iti_header" do
      cust_iti_header = CustItiHeader.create! valid_attributes
      get :show, {:id => cust_iti_header.to_param}, valid_session
      assigns(:cust_iti_header).should eq(cust_iti_header)
    end
  end

  describe "GET new" do
    it "assigns a new cust_iti_header as @cust_iti_header" do
      get :new, {}, valid_session
      assigns(:cust_iti_header).should be_a_new(CustItiHeader)
    end
  end

  describe "GET edit" do
    it "assigns the requested cust_iti_header as @cust_iti_header" do
      cust_iti_header = CustItiHeader.create! valid_attributes
      get :edit, {:id => cust_iti_header.to_param}, valid_session
      assigns(:cust_iti_header).should eq(cust_iti_header)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustItiHeader" do
        expect {
          post :create, {:cust_iti_header => valid_attributes}, valid_session
        }.to change(CustItiHeader, :count).by(1)
      end

      it "assigns a newly created cust_iti_header as @cust_iti_header" do
        post :create, {:cust_iti_header => valid_attributes}, valid_session
        assigns(:cust_iti_header).should be_a(CustItiHeader)
        assigns(:cust_iti_header).should be_persisted
      end

      it "redirects to the created cust_iti_header" do
        post :create, {:cust_iti_header => valid_attributes}, valid_session
        response.should redirect_to(CustItiHeader.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cust_iti_header as @cust_iti_header" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustItiHeader.any_instance.stub(:save).and_return(false)
        post :create, {:cust_iti_header => { "cust_iti_name" => "invalid value" }}, valid_session
        assigns(:cust_iti_header).should be_a_new(CustItiHeader)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustItiHeader.any_instance.stub(:save).and_return(false)
        post :create, {:cust_iti_header => { "cust_iti_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cust_iti_header" do
        cust_iti_header = CustItiHeader.create! valid_attributes
        # Assuming there are no other cust_iti_headers in the database, this
        # specifies that the CustItiHeader created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustItiHeader.any_instance.should_receive(:update).with({ "cust_iti_name" => "MyString" })
        put :update, {:id => cust_iti_header.to_param, :cust_iti_header => { "cust_iti_name" => "MyString" }}, valid_session
      end

      it "assigns the requested cust_iti_header as @cust_iti_header" do
        cust_iti_header = CustItiHeader.create! valid_attributes
        put :update, {:id => cust_iti_header.to_param, :cust_iti_header => valid_attributes}, valid_session
        assigns(:cust_iti_header).should eq(cust_iti_header)
      end

      it "redirects to the cust_iti_header" do
        cust_iti_header = CustItiHeader.create! valid_attributes
        put :update, {:id => cust_iti_header.to_param, :cust_iti_header => valid_attributes}, valid_session
        response.should redirect_to(cust_iti_header)
      end
    end

    describe "with invalid params" do
      it "assigns the cust_iti_header as @cust_iti_header" do
        cust_iti_header = CustItiHeader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustItiHeader.any_instance.stub(:save).and_return(false)
        put :update, {:id => cust_iti_header.to_param, :cust_iti_header => { "cust_iti_name" => "invalid value" }}, valid_session
        assigns(:cust_iti_header).should eq(cust_iti_header)
      end

      it "re-renders the 'edit' template" do
        cust_iti_header = CustItiHeader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustItiHeader.any_instance.stub(:save).and_return(false)
        put :update, {:id => cust_iti_header.to_param, :cust_iti_header => { "cust_iti_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cust_iti_header" do
      cust_iti_header = CustItiHeader.create! valid_attributes
      expect {
        delete :destroy, {:id => cust_iti_header.to_param}, valid_session
      }.to change(CustItiHeader, :count).by(-1)
    end

    it "redirects to the cust_iti_headers list" do
      cust_iti_header = CustItiHeader.create! valid_attributes
      delete :destroy, {:id => cust_iti_header.to_param}, valid_session
      response.should redirect_to(cust_iti_headers_url)
    end
  end

end
