require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DestItiHeadersController do
  login_user
  # This should return the minimal set of attributes required to create a valid
  # DestItiHeader. As you add validations to DestItiHeader, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.build(:dest_iti_header).attributes }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DestItiHeadersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dest_iti_headers as @dest_iti_headers" do
      dest_iti_header = DestItiHeader.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dest_iti_headers).should eq([dest_iti_header])
    end
  end

  describe "GET show" do
    it "assigns the requested dest_iti_header as @dest_iti_header" do
      dest_iti_header = DestItiHeader.create! valid_attributes
      get :show, {:id => dest_iti_header.to_param}, valid_session
      assigns(:dest_iti_header).should eq(dest_iti_header)
    end
  end

  describe "GET new" do
    it "assigns a new dest_iti_header as @dest_iti_header" do
      get :new, {}, valid_session
      assigns(:dest_iti_header).should be_a_new(DestItiHeader)
    end
  end

  describe "GET edit" do
    it "assigns the requested dest_iti_header as @dest_iti_header" do
      dest_iti_header = DestItiHeader.create! valid_attributes
      get :edit, {:id => dest_iti_header.to_param}, valid_session
      assigns(:dest_iti_header).should eq(dest_iti_header)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DestItiHeader" do
        expect {
          post :create, {:dest_iti_header => valid_attributes}, valid_session
        }.to change(DestItiHeader, :count).by(1)
      end

      it "assigns a newly created dest_iti_header as @dest_iti_header" do
        post :create, {:dest_iti_header => valid_attributes}, valid_session
        assigns(:dest_iti_header).should be_a(DestItiHeader)
        assigns(:dest_iti_header).should be_persisted
      end

      it "redirects to the created dest_iti_header" do
        post :create, {:dest_iti_header => valid_attributes}, valid_session
        response.should redirect_to(DestItiHeader.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dest_iti_header as @dest_iti_header" do
        # Trigger the behavior that occurs when invalid params are submitted
        DestItiHeader.any_instance.stub(:save).and_return(false)
        post :create, {:dest_iti_header => { "dest_iti_name" => "invalid value" }}, valid_session
        assigns(:dest_iti_header).should be_a_new(DestItiHeader)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DestItiHeader.any_instance.stub(:save).and_return(false)
        post :create, {:dest_iti_header => { "dest_iti_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dest_iti_header" do
        dest_iti_header = DestItiHeader.create! valid_attributes
        # Assuming there are no other dest_iti_headers in the database, this
        # specifies that the DestItiHeader created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DestItiHeader.any_instance.should_receive(:update).with({ "dest_iti_name" => "MyString" })
        put :update, {:id => dest_iti_header.to_param, :dest_iti_header => { "dest_iti_name" => "MyString" }}, valid_session
      end

      it "assigns the requested dest_iti_header as @dest_iti_header" do
        dest_iti_header = DestItiHeader.create! valid_attributes
        put :update, {:id => dest_iti_header.to_param, :dest_iti_header => valid_attributes}, valid_session
        assigns(:dest_iti_header).should eq(dest_iti_header)
      end

      it "redirects to the dest_iti_header" do
        dest_iti_header = DestItiHeader.create! valid_attributes
        put :update, {:id => dest_iti_header.to_param, :dest_iti_header => valid_attributes}, valid_session
        response.should redirect_to(dest_iti_header)
      end
    end

    describe "with invalid params" do
      it "assigns the dest_iti_header as @dest_iti_header" do
        dest_iti_header = DestItiHeader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DestItiHeader.any_instance.stub(:save).and_return(false)
        put :update, {:id => dest_iti_header.to_param, :dest_iti_header => { "dest_iti_name" => "invalid value" }}, valid_session
        assigns(:dest_iti_header).should eq(dest_iti_header)
      end

      it "re-renders the 'edit' template" do
        dest_iti_header = DestItiHeader.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DestItiHeader.any_instance.stub(:save).and_return(false)
        put :update, {:id => dest_iti_header.to_param, :dest_iti_header => { "dest_iti_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dest_iti_header" do
      dest_iti_header = DestItiHeader.create! valid_attributes
      expect {
        delete :destroy, {:id => dest_iti_header.to_param}, valid_session
      }.to change(DestItiHeader, :count).by(-1)
    end

    it "redirects to the dest_iti_headers list" do
      dest_iti_header = DestItiHeader.create! valid_attributes
      delete :destroy, {:id => dest_iti_header.to_param}, valid_session
      response.should redirect_to(dest_iti_headers_url)
    end
  end

end
