require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ItiDayDetailsController do

  # This should return the minimal set of attributes required to create a valid
  # ItiDayDetail. As you add validations to ItiDayDetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.build(:iti_day_detail).attributes }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ItiDayDetailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all iti_day_details as @iti_day_details" do
      iti_day_detail = ItiDayDetail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:iti_day_details).should eq([iti_day_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested iti_day_detail as @iti_day_detail" do
      iti_day_detail = ItiDayDetail.create! valid_attributes
      get :show, {:id => iti_day_detail.to_param}, valid_session
      assigns(:iti_day_detail).should eq(iti_day_detail)
    end
  end

  describe "GET new" do
    it "assigns a new iti_day_detail as @iti_day_detail" do
      get :new, {}, valid_session
      assigns(:iti_day_detail).should be_a_new(ItiDayDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested iti_day_detail as @iti_day_detail" do
      iti_day_detail = ItiDayDetail.create! valid_attributes
      get :edit, {:id => iti_day_detail.to_param}, valid_session
      assigns(:iti_day_detail).should eq(iti_day_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ItiDayDetail" do
        expect {
          post :create, {:iti_day_detail => valid_attributes}, valid_session
        }.to change(ItiDayDetail, :count).by(1)
      end

      it "assigns a newly created iti_day_detail as @iti_day_detail" do
        post :create, {:iti_day_detail => valid_attributes}, valid_session
        assigns(:iti_day_detail).should be_a(ItiDayDetail)
        assigns(:iti_day_detail).should be_persisted
      end

      it "redirects to the created iti_day_detail" do
        post :create, {:iti_day_detail => valid_attributes}, valid_session
        response.should redirect_to(ItiDayDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved iti_day_detail as @iti_day_detail" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItiDayDetail.any_instance.stub(:save).and_return(false)
        post :create, {:iti_day_detail => { "iti_header_id" => "invalid value" }}, valid_session
        assigns(:iti_day_detail).should be_a_new(ItiDayDetail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ItiDayDetail.any_instance.stub(:save).and_return(false)
        post :create, {:iti_day_detail => { "iti_header_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested iti_day_detail" do
        iti_day_detail = ItiDayDetail.create! valid_attributes
        # Assuming there are no other iti_day_details in the database, this
        # specifies that the ItiDayDetail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ItiDayDetail.any_instance.should_receive(:update).with({ "iti_header_id" => "1" })
        put :update, {:id => iti_day_detail.to_param, :iti_day_detail => { "iti_header_id" => "1" }}, valid_session
      end

      it "assigns the requested iti_day_detail as @iti_day_detail" do
        iti_day_detail = ItiDayDetail.create! valid_attributes
        put :update, {:id => iti_day_detail.to_param, :iti_day_detail => valid_attributes}, valid_session
        assigns(:iti_day_detail).should eq(iti_day_detail)
      end

      it "redirects to the iti_day_detail" do
        iti_day_detail = ItiDayDetail.create! valid_attributes
        put :update, {:id => iti_day_detail.to_param, :iti_day_detail => valid_attributes}, valid_session
        response.should redirect_to(iti_day_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the iti_day_detail as @iti_day_detail" do
        iti_day_detail = ItiDayDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItiDayDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => iti_day_detail.to_param, :iti_day_detail => { "iti_header_id" => "invalid value" }}, valid_session
        assigns(:iti_day_detail).should eq(iti_day_detail)
      end

      it "re-renders the 'edit' template" do
        iti_day_detail = ItiDayDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ItiDayDetail.any_instance.stub(:save).and_return(false)
        put :update, {:id => iti_day_detail.to_param, :iti_day_detail => { "iti_header_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested iti_day_detail" do
      iti_day_detail = ItiDayDetail.create! valid_attributes
      expect {
        delete :destroy, {:id => iti_day_detail.to_param}, valid_session
      }.to change(ItiDayDetail, :count).by(-1)
    end

    it "redirects to the iti_day_details list" do
      iti_day_detail = ItiDayDetail.create! valid_attributes
      delete :destroy, {:id => iti_day_detail.to_param}, valid_session
      response.should redirect_to(iti_day_details_url)
    end
  end

end
