require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PoaTypesController do
  login_user
  # This should return the minimal set of attributes required to create a valid
  # PoaType. As you add validations to PoaType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "poa_type" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PoaTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all poa_types as @poa_types" do
      poa_type = PoaType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:poa_types).should eq([poa_type])
    end
  end

  describe "GET show" do
    it "assigns the requested poa_type as @poa_type" do
      poa_type = PoaType.create! valid_attributes
      get :show, {:id => poa_type.to_param}, valid_session
      assigns(:poa_type).should eq(poa_type)
    end
  end

  describe "GET new" do
    it "assigns a new poa_type as @poa_type" do
      get :new, {}, valid_session
      assigns(:poa_type).should be_a_new(PoaType)
    end
  end

  describe "GET edit" do
    it "assigns the requested poa_type as @poa_type" do
      poa_type = PoaType.create! valid_attributes
      get :edit, {:id => poa_type.to_param}, valid_session
      assigns(:poa_type).should eq(poa_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PoaType" do
        expect {
          post :create, {:poa_type => valid_attributes}, valid_session
        }.to change(PoaType, :count).by(1)
      end

      it "assigns a newly created poa_type as @poa_type" do
        post :create, {:poa_type => valid_attributes}, valid_session
        assigns(:poa_type).should be_a(PoaType)
        assigns(:poa_type).should be_persisted
      end

      it "redirects to the created poa_type" do
        post :create, {:poa_type => valid_attributes}, valid_session
        response.should redirect_to(PoaType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved poa_type as @poa_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        PoaType.any_instance.stub(:save).and_return(false)
        post :create, {:poa_type => { "poa_type" => "invalid value" }}, valid_session
        assigns(:poa_type).should be_a_new(PoaType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PoaType.any_instance.stub(:save).and_return(false)
        post :create, {:poa_type => { "poa_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested poa_type" do
        poa_type = PoaType.create! valid_attributes
        # Assuming there are no other poa_types in the database, this
        # specifies that the PoaType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PoaType.any_instance.should_receive(:update).with({ "poa_type" => "MyString" })
        put :update, {:id => poa_type.to_param, :poa_type => { "poa_type" => "MyString" }}, valid_session
      end

      it "assigns the requested poa_type as @poa_type" do
        poa_type = PoaType.create! valid_attributes
        put :update, {:id => poa_type.to_param, :poa_type => valid_attributes}, valid_session
        assigns(:poa_type).should eq(poa_type)
      end

      it "redirects to the poa_type" do
        poa_type = PoaType.create! valid_attributes
        put :update, {:id => poa_type.to_param, :poa_type => valid_attributes}, valid_session
        response.should redirect_to(poa_type)
      end
    end

    describe "with invalid params" do
      it "assigns the poa_type as @poa_type" do
        poa_type = PoaType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PoaType.any_instance.stub(:save).and_return(false)
        put :update, {:id => poa_type.to_param, :poa_type => { "poa_type" => "invalid value" }}, valid_session
        assigns(:poa_type).should eq(poa_type)
      end

      it "re-renders the 'edit' template" do
        poa_type = PoaType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PoaType.any_instance.stub(:save).and_return(false)
        put :update, {:id => poa_type.to_param, :poa_type => { "poa_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested poa_type" do
      poa_type = PoaType.create! valid_attributes
      expect {
        delete :destroy, {:id => poa_type.to_param}, valid_session
      }.to change(PoaType, :count).by(-1)
    end

    it "redirects to the poa_types list" do
      poa_type = PoaType.create! valid_attributes
      delete :destroy, {:id => poa_type.to_param}, valid_session
      response.should redirect_to(poa_types_url)
    end
  end

end
