require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PointsOfAttractionsController do
  login_user
  # This should return the minimal set of attributes required to create a valid
  # PointsOfAttraction. As you add validations to PointsOfAttraction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { FactoryGirl.build(:points_of_attraction).attributes }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PointsOfAttractionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all points_of_attractions as @points_of_attractions" do
      points_of_attraction = PointsOfAttraction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:points_of_attractions).should eq([points_of_attraction])
    end
  end

  describe "GET show" do
    it "assigns the requested points_of_attraction as @points_of_attraction" do
      points_of_attraction = PointsOfAttraction.create! valid_attributes
      get :show, {:id => points_of_attraction.to_param}, valid_session
      assigns(:points_of_attraction).should eq(points_of_attraction)
    end
  end

  describe "GET new" do
    it "assigns a new points_of_attraction as @points_of_attraction" do
      get :new, {}, valid_session
      assigns(:points_of_attraction).should be_a_new(PointsOfAttraction)
    end
  end

  describe "GET edit" do
    it "assigns the requested points_of_attraction as @points_of_attraction" do
      points_of_attraction = PointsOfAttraction.create! valid_attributes
      get :edit, {:id => points_of_attraction.to_param}, valid_session
      assigns(:points_of_attraction).should eq(points_of_attraction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PointsOfAttraction" do
        expect {
          post :create, {:points_of_attraction => valid_attributes}, valid_session
        }.to change(PointsOfAttraction, :count).by(1)
      end

      it "assigns a newly created points_of_attraction as @points_of_attraction" do
        post :create, {:points_of_attraction => valid_attributes}, valid_session
        assigns(:points_of_attraction).should be_a(PointsOfAttraction)
        assigns(:points_of_attraction).should be_persisted
      end

      it "redirects to the created points_of_attraction" do
        post :create, {:points_of_attraction => valid_attributes}, valid_session
        response.should redirect_to(PointsOfAttraction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved points_of_attraction as @points_of_attraction" do
        # Trigger the behavior that occurs when invalid params are submitted
        PointsOfAttraction.any_instance.stub(:save).and_return(false)
        post :create, {:points_of_attraction => { "destination_id" => "invalid value" }}, valid_session
        assigns(:points_of_attraction).should be_a_new(PointsOfAttraction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PointsOfAttraction.any_instance.stub(:save).and_return(false)
        post :create, {:points_of_attraction => { "destination_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested points_of_attraction" do
        points_of_attraction = PointsOfAttraction.create! valid_attributes
        # Assuming there are no other points_of_attractions in the database, this
        # specifies that the PointsOfAttraction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PointsOfAttraction.any_instance.should_receive(:update).with({ "destination_id" => "1" })
        put :update, {:id => points_of_attraction.to_param, :points_of_attraction => { "destination_id" => "1" }}, valid_session
      end

      it "assigns the requested points_of_attraction as @points_of_attraction" do
        points_of_attraction = PointsOfAttraction.create! valid_attributes
        put :update, {:id => points_of_attraction.to_param, :points_of_attraction => valid_attributes}, valid_session
        assigns(:points_of_attraction).should eq(points_of_attraction)
      end

      it "redirects to the points_of_attraction" do
        points_of_attraction = PointsOfAttraction.create! valid_attributes
        put :update, {:id => points_of_attraction.to_param, :points_of_attraction => valid_attributes}, valid_session
        response.should redirect_to(points_of_attraction)
      end
    end

    describe "with invalid params" do
      it "assigns the points_of_attraction as @points_of_attraction" do
        points_of_attraction = PointsOfAttraction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PointsOfAttraction.any_instance.stub(:save).and_return(false)
        put :update, {:id => points_of_attraction.to_param, :points_of_attraction => { "destination_id" => "invalid value" }}, valid_session
        assigns(:points_of_attraction).should eq(points_of_attraction)
      end

      it "re-renders the 'edit' template" do
        points_of_attraction = PointsOfAttraction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PointsOfAttraction.any_instance.stub(:save).and_return(false)
        put :update, {:id => points_of_attraction.to_param, :points_of_attraction => { "destination_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested points_of_attraction" do
      points_of_attraction = PointsOfAttraction.create! valid_attributes
      expect {
        delete :destroy, {:id => points_of_attraction.to_param}, valid_session
      }.to change(PointsOfAttraction, :count).by(-1)
    end

    it "redirects to the points_of_attractions list" do
      points_of_attraction = PointsOfAttraction.create! valid_attributes
      delete :destroy, {:id => points_of_attraction.to_param}, valid_session
      response.should redirect_to(points_of_attractions_url)
    end
  end

end
